/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.applicationtest;

public class App {

    public String getGreeting()
    {
        return "Hello world.";
    }

    public static void main(String[] args)
    {
        System.out.println(new App().getGreeting());

        for (String arg : args)
        {
            System.out.println(arg);
        }
    }
}
